import { execSync } from 'child_process'
import fs from 'fs'
import path from 'path'

async function runVerification() {
  console.log('====================================================')
  console.log('🔍 BambiGO ODPT Integration Verification System')
  console.log('====================================================')
  console.log('Date:', new Date().toLocaleString())
  console.log('Environment:', process.env.NODE_ENV || 'development')
  console.log('----------------------------------------------------\n')

  const results = {
    connection: { status: 'PENDING', duration: 0 },
    transformation: { status: 'PENDING', duration: 0 },
    e2e: { status: 'PENDING', duration: 0 },
  }

  try {
    // 1. Connection Test
    console.log('1. Testing API Connectivity & Performance...')
    const startConn = Date.now()
    execSync('npx vitest run tests/odpt_verification/odpt_connection.spec.ts', { stdio: 'inherit' })
    results.connection.status = 'PASS'
    results.connection.duration = Date.now() - startConn

    // 2. Data Transformation Test
    console.log('\n2. Testing Data Transformation Logic...')
    const startTrans = Date.now()
    execSync('npx vitest run tests/odpt_verification/data_transformation.spec.ts', { stdio: 'inherit' })
    results.transformation.status = 'PASS'
    results.transformation.duration = Date.now() - startTrans

    // 3. E2E Flow Test
    console.log('\n3. Testing End-to-End Pipeline Flow...')
    const startE2E = Date.now()
    execSync('npx vitest run tests/odpt_verification/e2e_flow.spec.ts', { stdio: 'inherit' })
    results.e2e.status = 'PASS'
    results.e2e.duration = Date.now() - startE2E

    generateReport(results)
  } catch (err) {
    console.error('\n❌ Verification failed during test execution.')
    // Still try to generate partial report
    generateReport(results, err instanceof Error ? err.message : String(err))
    process.exit(1)
  }
}

function generateReport(results: any, error?: string) {
  const reportPath = path.join(process.cwd(), 'docs', 'ODPT_VERIFICATION_REPORT.md')
  const reportContent = `
# ODPT Integration Verification Report
**Date:** ${new Date().toISOString()}
**Overall Status:** ${error ? '🔴 FAILED' : '🟢 PASSED'}

## 📊 Summary
| Category | Status | Duration |
| :--- | :--- | :--- |
| API Connection | ${results.connection.status} | ${results.connection.duration}ms |
| Data Transformation | ${results.transformation.status} | ${results.transformation.duration}ms |
| E2E Pipeline | ${results.e2e.status} | ${results.e2e.duration}ms |

${error ? `## ❌ Error Log\n\`\`\`\n${error}\n\`\`\`` : ''}

## 📝 Recommendations
- **Connection**: Ensure \`ODPT_API_TOKEN\` is rotated every 12 months.
- **Performance**: Monitor for latency spikes in \`odpt.Operator:JR-East\` queries (highest data volume).
- **Quality**: Regularly verify \`trap_warnings\` against actual station layouts.

---
Generated by BambiGO Verification Bot
`
  if (!fs.existsSync(path.dirname(reportPath))) fs.mkdirSync(path.dirname(reportPath), { recursive: true })
  fs.writeFileSync(reportPath, reportContent)
  console.log(`\n✅ Report generated: ${reportPath}`)
}

runVerification().catch(console.error)
